### ISSUE TITLE
Switching themes will cause an error

### ISSUE THREAD

**Issue by ofseed** [utilyre/barbecue.nvim#44]
As the title says, after neovim starts, if you change the current theme, an error will be reported, and the color of barbecue will disappear.

before:
![image](https://user-images.githubusercontent.com/61115159/210154736-da9e7550-86ae-41ce-8d8d-bdac6f2304ed.png)

after changing the theme (even changing to the same theme):
![image](https://user-images.githubusercontent.com/61115159/210154766-f3d409a8-a617-4747-94c3-044fd8e7c018.png)

Error message:
```
Error executing vim.schedule lua callback: ...s/code/nvim/barbecue.nvim/lua/barbecue/ui/components.lua:26: invalid key: 
stack traceback:
	[C]: in function 'nvim_set_hl'
	...s/code/nvim/barbecue.nvim/lua/barbecue/ui/components.lua:26: in function 'get_file_icon'
	...s/code/nvim/barbecue.nvim/lua/barbecue/ui/components.lua:110: in function 'get_basename'
	...ed/Documents/code/nvim/barbecue.nvim/lua/barbecue/ui.lua:62: in function 'create_entries'
	...ed/Documents/code/nvim/barbecue.nvim/lua/barbecue/ui.lua:146: in function <...ed/Documents/code/nvim/barbecue.nvim/lua/barbecue/ui.lua:135>
```
Note the error only generates when opening a new type of file.

**Comment by ofseed** [comment]
By the way, the `auto` theme seems to be useless.
Even I am using catppuccin as my colorscheme,
The color will be the default unless I set the theme to `catppuccin` explicitly.

**Comment by utilyre** [comment]
Hello. Checkout `feature/theme-generation`, it should be working.

**Comment by ofseed** [comment]
On this branch, there must be errors generated at the moment of switching:
```
Error executing lua callback: ...cal/share/nvim/lazy/barbecue.nvim/lua/barbecue/theme.lua:185: invalid key: 
stack traceback:
	[C]: in function 'nvim_set_hl'
	...cal/share/nvim/lazy/barbecue.nvim/lua/barbecue/theme.lua:185: in function 'load'
	...ed/.local/share/nvim/lazy/barbecue.nvim/lua/barbecue.lua:56: in function <...ed/.local/share/nvim/lazy/barbecue.nvim/lua/barbecue.lua:55>
```
Colors other than file icons seem to work fine though:
![image](https://user-images.githubusercontent.com/61115159/210160550-f56ccead-cfa1-4261-bdf2-e01528a26f02.png)

**Comment by nyngwang** [comment]
@utilyre Hi, sir. What the OP has reported is exactly the same thing I experienced during my debugging of #40. I highly recommend you write some tests investigating the following linked lines, especially the for-loop(line 71~78).

These are some of my conclusions, which hopefully can save you some time:

1. I'm pretty sure that this problem is related to the way lazy.nvim designed to run those `config = ...`. If you log the two loop variables, i.e. `key, name`, at line 71, you will see those values printed before NeoVim started.
2. But then, lazy.nvim seems to *discard* these values thereafter. So, in fact, at line 75 the API `vim.tbl_extend` will have a `theme[nil]` passing in, which causes the error message:

    ```
    [...] invalid key: 
    stack traceback:
	    [C]: in function 'nvim_set_hl'
    [...]
    ```

3. All your current commits don't fix the coloring issue mentioned in #40 as far as I know. I still get everything `cleared` from `:hi`(as per the img I provided below)

    <img src="https://user-images.githubusercontent.com/24765272/210171983-544e82eb-bc42-4813-abed-efd1d00b196f.png" width="400">

4. Based on the error message provided by @ofseed above, he/she is using lazy.nvim. So my conclusions apply.

    > 	[C]: in function 'nvim_set_hl'
    >	...cal/share/nvim/**lazy**/barbecue.nvim/lua/barbecue/theme.lua:185: in function 'load'

https://github.com/utilyre/barbecue.nvim/blob/95f145a9445df954918e3751dd51ba2446606a31/lua/barbecue/theme.lua#L61-L78

**Comment by utilyre** [comment]
I don't think it is the case here, but i guess it's worth mentioning that `barbecue.setup` should be called once the colorscheme and nvim-cmp (because some colorschemes, like tokyonight, do not define all of the cmp highlights which are being used as fallbacks) are loaded for it to function correctly.

I'm planning to make the `auto` option only rely on the builtin neovim highlight groups though.

**Comment by utilyre** [comment]
Btw @nyngwang are you on nvim nightly? If so try out nvim stable and see if the bug still persists.

However, with the minimal config you gave me and the latest commit of `main`, this `invalid key:` issue is fixed (at least on my machine).

**Comment by nyngwang** [comment]
> Btw @nyngwang are you on nvim nightly?

Yes. But I just rollbacked to neovim/neovim@99cf111 since upstream is doing some breaking changes on TUI and it breaks my noice.nvim now.

**Comment by utilyre** [comment]
> So in your current setup those highlight groups from :hi are not cleared?

No, they get created based on the loaded theme. I might be able to spot the issue if you give me your dotfiles.

**Comment by utilyre** [comment]
Made some changes again for relying on the builtin highlights.

I'm not quite sure which version of nvim brought these `@enum`-like hls, if somebody knows please tell me so that I can bump the required version of neovim in readme.

However, I tested them and they seem to be defined with nvim out of the box.

**Comment by nyngwang** [comment]
> I'm not quite sure which version of nvim brought these `@enum`-like hls [...]

I noticed this too recently. IIRC, there is no hl groups named like this before.

**Comment by nyngwang** [comment]
Got error if I set the `autocmd` myself. Here is my config:

```lua
use {
  'utilyre/barbecue.nvim', enabled = true,
  dependencies = {
    'neovim/nvim-lspconfig',
    'smiteshp/nvim-navic',
    'kyazdani42/nvim-web-devicons',
  },
  config = function ()
    require('barbecue').setup {
      attach_navic = false, -- attach navic to LSPs automatically.
      create_autocmd = false,
    }
    vim.api.nvim_create_autocmd({ 'CursorHold' }, {
      callback = function()
        require('barbecue.ui').update()
      end,
    })
    -- If I use the following autocmd then I will get an error.
    vim.api.nvim_create_autocmd({ 'ColorScheme' }, {
      callback = function()
        require('data.barbecue').set_background('Normal', 'guibg')
      end,
    })
  end
}
```

```
   Error  22:16:44 msg_show.lua_error Error executing vim.schedule lua callback: ...e/nvim/lazy/barbecue.nvim/lua/barbecue/ui/components.lua:27: invalid key: 
stack traceback:
	[C]: in function 'nvim_set_hl'
	...e/nvim/lazy/barbecue.nvim/lua/barbecue/ui/components.lua:27: in function 'get_file_icon'
	...e/nvim/lazy/barbecue.nvim/lua/barbecue/ui/components.lua:111: in function 'get_basename'
	....local/share/nvim/lazy/barbecue.nvim/lua/barbecue/ui.lua:62: in function 'create_entries'
	....local/share/nvim/lazy/barbecue.nvim/lua/barbecue/ui.lua:149: in function <....local/share/nvim/lazy/barbecue.nvim/lua/barbecue/ui.lua:138>
```

**Comment by utilyre** [comment]
You should be using the `theme` option in config (see [Configuration](https://github.com/utilyre/barbecue.nvim/tree/1006f449e7bef625e706d53adfe944647c6a990d#-configuration)).

In case you want to override it by hand, you should go to [Template](https://github.com/utilyre/barbecue.nvim/blob/ede3191f54ef08f8c22dfb01666ff99ad121a0be/CODE_OF_CONDUCT.md#template) and copy `M` variable's value and paste it as `theme` in your config. Then start changing the colors. (removing some elements, say `context_file`, is okay since it falls back to the auto detected/generated theme)

**Comment by utilyre** [comment]
Sorry, I forgot to say the `feature/theme-generation` branch had been merged yesterday.

**Comment by nyngwang** [comment]
> In case you want to override it by hand, you should go to [Template](https://github.com/utilyre/barbecue.nvim/blob/ede3191f54ef08f8c22dfb01666ff99ad121a0be/CODE_OF_CONDUCT.md#template) and copy M variable's value and paste it as theme in your config. [...]

But I still prefer the old way of using `autocmd` on `ColorScheme` to dynamically change the `guibg` of all `barbecue_*`. With theme in config it is just a fixed value...

**Comment by nyngwang** [comment]
@utilyre Oh wait, what I just said seems to be fixed after some updates of lazy.nvim secs ago. Everything is working now!

**Comment by utilyre** [comment]
> @utilyre But I still prefer the old way of using autocmd on ColorScheme to dynamically change the guibg of all barbecue_*. With theme in config it is just a fixed value.

Honestly, it's not possible to satisfy everyone. As people wanted in #30, I made this mechanism of defining highlight groups dynamically which is inspired by bufferline.nvim and lualine.nvim. So I think going back to the way it was before is regression.

> But it's still possible to get the following error when I change between colorschemes

I cannot reproduce this, make sure to use nvim stable and also change your config to use the `theme` option in `.setup()` and see if it is still giving you the error.

**Comment by nyngwang** [comment]
> [...] So I think going back to the way it was before is regression.

Well, even after **removing** all my codes for "using `autocmd` on `ColorScheme` to dynamically change the `guibg`", I still have many errors by simply changing between installed colorschemes:

https://user-images.githubusercontent.com/24765272/210536242-c9c4bcd6-12da-497d-9d02-d2950d0e6880.mov

> I cannot reproduce this, [...]

Do you use lazy.nvim? I believe the trouble will still exist even if I use nvim-0.8. The problem is on the API `nvim_set_hl`, which if it's buggy on 0.9 it's not possible to fix it on 0.8.

---

to reproduce you can use this config:

```lua
use {
  'utilyre/barbecue.nvim', enabled = true,
  dependencies = {
    'neovim/nvim-lspconfig',
    'SmiteshP/nvim-navic',
    'nvim-tree/nvim-web-devicons',
  },
  config = function ()
    require('barbecue').setup {
      attach_navic = false, -- attach navic to LSPs automatically.
      create_autocmd = false,
      theme = 'auto',
    }
    vim.api.nvim_create_autocmd({ 'CursorHold' }, {
      group = 'nvim_ide.lua',
      callback = function()
        require('barbecue.ui').update()
      end,
    })
  end
}
```

**Comment by utilyre** [comment]
Should be fixed now.

**Comment by nyngwang** [comment]
@utilyre Hi, I just tested the branch, and these are my observations:

- No longer seeing any error as mentioned.
- I still have a chance to see the default(i.e. `guibg=#808080`) being used when I first start neovim and restore my session.
- I still have a chance to see the default(i.e. `guibg=#808080`) being used after I switched to another colorscheme. (so my `autocmd` on `ColorScheme` that makes use of `hi barbecue_*` somehow cannot overwrite the one that was being used.)

**Comment by nyngwang** [comment]
I just checked the plugin `nvim-treesitter-context` and the can work with the traditional `hi ...` on `ColorScheme` without error. There are only 3 lines for setting up those highlight groups that can change the background color and it works well with lazy.nvim. Maybe it would help you debug/improve/refactor/wahtsoever.

I have no more energy debugging this. Sorry for maybe being annoying. Leaving...

**Comment by utilyre** [comment]
@nyngwang thanks for being helpful along the way.

I've also been experiencing the `default.lua` theme not being able to extract some colors from the colorscheme. So I think it's more likely a weird loading order problem with lazy.nvim.

@ofseed please consider closing issue if the mentioned branch is working fine. It'll be merged into `main` once [#186](https://github.com/nvim-tree/nvim-web-devicons/pull/186) is merged.

**Comment by utilyre** [comment]
It's been two weeks, so I'll close the issue myself. Feel free to re-open if this happens again.

**Comment by ofseed** [comment]
Sorry for missing the previous notification, thank you so much for your work. I have also been using barbecue since this branch was merged into master two weeks ago and it has worked fine.
